import "Root/layouts/index.html";
import "Root/pages/home.html";
import "Root/pages/about.html";
import "Root/pages/care.html";
import "Root/pages/faq.html";
import "Root/app.scss";
import "Root/routers/router";
import "Root/module/_header.js";
import "Root/module/_slider.js";
